import { CountryCode } from './country-code';

export const ISO_3166_1_CODES: CountryCode[] = [
    { prefix: '+93', code: 'AF', country: 'Afghanistan ' },
  { prefix: '+355', code: 'AL', country: 'Albania ' },
  { prefix: '+213', code: 'DZ', country: 'Algeria ' },
  { prefix: '+1-684', code: 'AS', country: 'American Samoa' },
  { prefix: '+376', code: 'AD', country: 'Andorra, Principality of ' },
  { prefix: '+244', code: 'AO', country: 'Angola' },
  { prefix: '+1-264', code: 'AI', country: 'Anguilla ' },
  { prefix: '+672', code: 'AQ', country: 'Antarctica' },
  { prefix: '+1-268', code: 'AG', country: 'Antigua and Barbuda' },
  { prefix: '+54', code: 'AR', country: 'Argentina ' },
  { prefix: '+374', code: 'AM', country: 'Armenia' },
  { prefix: '+297', code: 'AW', country: 'Aruba' },
  { prefix: '+61', code: 'AU', country: 'Australia' },
  { prefix: '+43', code: 'AT', country: 'Austria' },
  {
    prefix: '+994',
    code: 'AZ',
    country:
      'Azerbaijan or Azerbaidjan (Former Azerbaijan Soviet Socialist Republic)',
  },
  { prefix: '+1-242', code: 'BS', country: 'Bahamas, Commonwealth of The' },
  {
    prefix: '+973',
    code: 'BH',
    country: 'Bahrain, Kingdom of (Former Dilmun)',
  },
  { prefix: '+880', code: 'BD', country: 'Bangladesh (Former East Pakistan)' },
  { prefix: '+1-246', code: 'BB', country: 'Barbados ' },
  {
    prefix: '+375',
    code: 'BY',
    country:
      'Belarus (Former Belorussian [Byelorussian] Soviet Socialist Republic)',
  },
  { prefix: '+32', code: 'BE', country: 'Belgium ' },
  { prefix: '+501', code: 'BZ', country: 'Belize (Former British Honduras)' },
  { prefix: '+229', code: 'BJ', country: 'Benin (Former Dahomey)' },
  { prefix: '+1-441', code: 'BM', country: 'Bermuda ' },
  { prefix: '+975', code: 'BT', country: 'Bhutan, Kingdom of' },
  { prefix: '+591', code: 'BO', country: 'Bolivia ' },
  { prefix: '+387', code: 'BA', country: 'Bosnia and Herzegovina ' },
  { prefix: '+267', code: 'BW', country: 'Botswana (Former Bechuanaland)' },
  { prefix: '+55', code: 'BR', country: 'Brazil ' },
  { prefix: '+673', code: 'BN', country: 'Brunei (Negara Brunei Darussalam) ' },
  { prefix: '+359', code: 'BG', country: 'Bulgaria ' },
  { prefix: '+226', code: 'BF', country: 'Burkina Faso (Former Upper Volta)' },
  { prefix: '+257', code: 'BI', country: 'Burundi (Former Urundi)' },
  {
    prefix: '+855',
    code: 'KH',
    country: 'Cambodia, Kingdom of (Former Khmer Republic, Kampuchea Republic)',
  },
  { prefix: '+237', code: 'CM', country: 'Cameroon (Former French Cameroon)' },
  { prefix: '+1', code: 'CA', country: 'Canada ' },
  { prefix: '+238', code: 'CV', country: 'Cape Verde ' },
  { prefix: '+1-345', code: 'KY', country: 'Cayman Islands ' },
  { prefix: '+236', code: 'CF', country: 'Central African Republic ' },
  { prefix: '+235', code: 'TD', country: 'Chad ' },
  { prefix: '+56', code: 'CL', country: 'Chile ' },
  { prefix: '+86', code: 'CN', country: 'China ' },
  { prefix: '+53', code: 'CX', country: 'Christmas Island ' },
  { prefix: '+61', code: 'CC', country: 'Cocos (Keeling) Islands ' },
  { prefix: '+57', code: 'CO', country: 'Colombia ' },
  { prefix: '+269', code: 'KM', country: 'Comoros, Union of the ' },
  {
    prefix: '+243',
    code: 'CD',
    country: 'Congo, Democratic Republic of the (Former Zaire) ',
  },
  { prefix: '+242', code: 'CG', country: 'Congo, Republic of the' },
  {
    prefix: '+682',
    code: 'CK',
    country: 'Cook Islands (Former Harvey Islands)',
  },
  { prefix: '+506', code: 'CR', country: 'Costa Rica ' },
  {
    prefix: '+225',
    code: 'CI',
    country: "Cote D'Ivoire (Former Ivory Coast) ",
  },
  { prefix: '+385', code: 'HR', country: 'Croatia (Hrvatska) ' },
  { prefix: '+53', code: 'CU', country: 'Cuba ' },
  { prefix: '+357', code: 'CY', country: 'Cyprus ' },
  { prefix: '+420', code: 'CZ', country: 'Czech Republic' },
  { prefix: '+45', code: 'DK', country: 'Denmark ' },
  {
    prefix: '+253',
    code: 'DJ',
    country:
      'Djibouti (Former French Territory of the Afars and Issas, French Somaliland)',
  },
  { prefix: '+1-767', code: 'DM', country: 'Dominica ' },
  { prefix: '+1-809', code: 'DO', country: 'Dominican Republic ' },
  {
    prefix: '+670',
    code: 'TP',
    country: 'East Timor (Former Portuguese Timor)',
  },
  { prefix: '+593 ', code: 'EC', country: 'Ecuador ' },
  {
    prefix: '+20',
    code: 'EG',
    country: 'Egypt (Former United Arab Republic - with Syria)',
  },
  { prefix: '+503', code: 'SV', country: 'El Salvador ' },
  {
    prefix: '+240',
    code: 'GQ',
    country: 'Equatorial Guinea (Former Spanish Guinea)',
  },
  {
    prefix: '+291',
    code: 'ER',
    country: 'Eritrea (Former Eritrea Autonomous Region in Ethiopia)',
  },
  {
    prefix: '+372',
    code: 'EE',
    country: 'Estonia (Former Estonian Soviet Socialist Republic)',
  },
  {
    prefix: '+251',
    code: 'ET',
    country: 'Ethiopia (Former Abyssinia, Italian East Africa)',
  },
  { prefix: '+500', code: 'FK', country: 'Falkland Islands (Islas Malvinas) ' },
  { prefix: '+298', code: 'FO', country: 'Faroe Islands ' },
  { prefix: '+679', code: 'FJ', country: 'Fiji ' },
  { prefix: '+358', code: 'FI', country: 'Finland ' },
  { prefix: '+33', code: 'FR', country: 'France ' },
  { prefix: '+594', code: 'GF', country: 'French Guiana or French Guyana ' },
  {
    prefix: '+689',
    code: 'PF',
    country: 'French Polynesia (Former French Colony of Oceania)',
  },
  { prefix: '+241', code: 'GA', country: 'Gabon (Gabonese Republic)' },
  { prefix: '+220', code: 'GM', country: 'Gambia, The ' },
  {
    prefix: '+995',
    code: 'GE',
    country: 'Georgia (Former Georgian Soviet Socialist Republic)',
  },
  { prefix: '+49', code: 'DE', country: 'Germany ' },
  { prefix: '+233', code: 'GH', country: 'Ghana (Former Gold Coast)' },
  { prefix: '+350', code: 'GI', country: 'Gibraltar ' },
  { prefix: '+30', code: 'GR', country: 'Greece ' },
  { prefix: '+299', code: 'GL', country: 'Greenland ' },
  { prefix: '+1-473', code: 'GD', country: 'Grenada ' },
  { prefix: '+590', code: 'GP', country: 'Guadeloupe' },
  { prefix: '+1-671', code: 'GU', country: 'Guam' },
  { prefix: '+502', code: 'GT', country: 'Guatemala ' },
  { prefix: '+224', code: 'GN', country: 'Guinea (Former French Guinea)' },
  {
    prefix: '+245',
    code: 'GW',
    country: 'Guinea-Bissau (Former Portuguese Guinea)',
  },
  { prefix: '+592', code: 'GY', country: 'Guyana (Former British Guiana)' },
  { prefix: '+509', code: 'HT', country: 'Haiti ' },
  { prefix: '+504', code: 'HN', country: 'Honduras ' },
  { prefix: '+852', code: 'HK', country: 'Hong Kong ' },
  { prefix: '+36', code: 'HU', country: 'Hungary ' },
  { prefix: '+354', code: 'IS', country: 'Iceland ' },
  { prefix: '+91', code: 'IN', country: 'India ' },
  {
    prefix: '+62',
    code: 'ID',
    country: 'Indonesia (Former Netherlands East Indies; Dutch East Indies)',
  },
  { prefix: '+98', code: 'IR', country: 'Iran, Islamic Republic of' },
  { prefix: '+964', code: 'IQ', country: 'Iraq ' },
  { prefix: '+353', code: 'IE', country: 'Ireland ' },
  { prefix: '+972', code: 'IL', country: 'Israel ' },
  { prefix: '+39', code: 'IT', country: 'Italy ' },
  { prefix: '+1-876', code: 'JM', country: 'Jamaica ' },
  { prefix: '+81', code: 'JP', country: 'Japan ' },
  { prefix: '+962', code: 'JO', country: 'Jordan (Former Transjordan)' },
  {
    prefix: '+7',
    code: 'KZ',
    country:
      'Kazakstan or Kazakhstan (Former Kazakh Soviet Socialist Republic)',
  },
  { prefix: '+254', code: 'KE', country: 'Kenya (Former British East Africa)' },
  {
    prefix: '+686',
    code: 'KI',
    country: 'Kiribati (Pronounced keer-ree-bahss) (Former Gilbert Islands)',
  },
  {
    prefix: '+850',
    code: 'KP',
    country: "Korea, Democratic People's Republic of (North Korea)",
  },
  { prefix: '+82', code: 'KR', country: 'Korea, Republic of (South Korea) ' },
  { prefix: '+965', code: 'KW', country: 'Kuwait ' },
  {
    prefix: '+996',
    code: 'KG',
    country:
      'Kyrgyzstan (Kyrgyz Republic) (Former Kirghiz Soviet Socialist Republic)',
  },
  {
    prefix: '+856',
    code: 'LA',
    country: "Lao People's Democratic Republic (Laos)",
  },
  {
    prefix: '+371',
    code: 'LV',
    country: 'Latvia (Former Latvian Soviet Socialist Republic)',
  },
  { prefix: '+961', code: 'LB', country: 'Lebanon ' },
  { prefix: '+266', code: 'LS', country: 'Lesotho (Former Basutoland)' },
  { prefix: '+231', code: 'LR', country: 'Liberia ' },
  { prefix: '+218', code: 'LY', country: 'Libya (Libyan Arab Jamahiriya)' },
  { prefix: '+423', code: 'LI', country: 'Liechtenstein ' },
  {
    prefix: '+370',
    code: 'LT',
    country: 'Lithuania (Former Lithuanian Soviet Socialist Republic)',
  },
  { prefix: '+352', code: 'LU', country: 'Luxembourg ' },
  { prefix: '+853', code: 'MO', country: 'Macau ' },
  {
    prefix: '+389',
    code: 'MK',
    country: 'Macedonia, The Former Yugoslav Republic of',
  },
  {
    prefix: '+261',
    code: 'MG',
    country: 'Madagascar (Former Malagasy Republic)',
  },
  {
    prefix: '+265',
    code: 'MW',
    country: 'Malawi (Former British Central African Protectorate, Nyasaland)',
  },
  { prefix: '+60', code: 'MY', country: 'Malaysia ' },
  { prefix: '+960', code: 'MV', country: 'Maldives ' },
  {
    prefix: '+223',
    code: 'ML',
    country: 'Mali (Former French Sudan and Sudanese Republic) ',
  },
  { prefix: '+356', code: 'MT', country: 'Malta ' },
  {
    prefix: '+692',
    code: 'MH',
    country:
      'Marshall Islands (Former Marshall Islands District - Trust Territory of the Pacific Islands)',
  },
  { prefix: '+596', code: 'MQ', country: 'Martinique (French) ' },
  { prefix: '+222', code: 'MR', country: 'Mauritania ' },
  { prefix: '+230', code: 'MU', country: 'Mauritius ' },
  {
    prefix: '+269',
    code: 'YT',
    country: 'Mayotte (Territorial Collectivity of Mayotte)',
  },
  { prefix: '+52', code: 'MX', country: 'Mexico ' },
  {
    prefix: '+691',
    code: 'FM',
    country:
      'Micronesia, Federated States of (Former Ponape, Truk, and Yap Districts - Trust Territory of the Pacific Islands)',
  },
  { prefix: '+373', code: 'MD', country: 'Moldova, Republic of' },
  { prefix: '+377', code: 'MC', country: 'Monaco, Principality of' },
  { prefix: '+976', code: 'MN', country: 'Mongolia (Former Outer Mongolia)' },
  { prefix: '+1-664', code: 'MS', country: 'Montserrat ' },
  { prefix: '+212', code: 'MA', country: 'Morocco ' },
  {
    prefix: '+258',
    code: 'MZ',
    country: 'Mozambique (Former Portuguese East Africa)',
  },
  { prefix: '+95', code: 'MM', country: 'Myanmar, Union of (Former Burma)' },
  {
    prefix: '+264',
    code: 'NA',
    country: 'Namibia (Former German Southwest Africa, South-West Africa)',
  },
  { prefix: '+674', code: 'NR', country: 'Nauru (Former Pleasant Island)' },
  { prefix: '+977', code: 'NP', country: 'Nepal ' },
  { prefix: '+31', code: 'NL', country: 'Netherlands ' },
  {
    prefix: '+599',
    code: 'AN',
    country: 'Netherlands Antilles (Former Curacao and Dependencies)',
  },
  { prefix: '+687', code: 'NC', country: 'New Caledonia ' },
  { prefix: '+64', code: 'NZ', country: 'New Zealand (Aotearoa) ' },
  { prefix: '+505', code: 'NI', country: 'Nicaragua ' },
  { prefix: '+227', code: 'NE', country: 'Niger ' },
  { prefix: '+234', code: 'NG', country: 'Nigeria ' },
  { prefix: '+683', code: 'NU', country: 'Niue (Former Savage Island)' },
  { prefix: '+672', code: 'NF', country: 'Norfolk Island ' },
  {
    prefix: '+1-670',
    code: 'MP',
    country:
      'Northern Mariana Islands (Former Mariana Islands District - Trust Territory of the Pacific Islands)',
  },
  { prefix: '+47', code: 'NO', country: 'Norway ' },
  {
    prefix: '+968',
    code: 'OM',
    country: 'Oman, Sultanate of (Former Muscat and Oman)',
  },
  { prefix: '+92', code: 'PK', country: 'Pakistan (Former West Pakistan)' },
  {
    prefix: '+680',
    code: 'PW',
    country:
      'Palau (Former Palau District - Trust Terriroty of the Pacific Islands)',
  },
  { prefix: '+970', code: 'PS', country: 'Palestinian State (Proposed)' },
  { prefix: '+507', code: 'PA', country: 'Panama ' },
  {
    prefix: '+675',
    code: 'PG',
    country: 'Papua New Guinea (Former Territory of Papua and New Guinea)',
  },
  { prefix: '+595', code: 'PY', country: 'Paraguay ' },
  { prefix: '+51', code: 'PE', country: 'Peru ' },
  { prefix: '+63', code: 'PH', country: 'Philippines ' },
  { prefix: '+48', code: 'PL', country: 'Poland ' },
  { prefix: '+351', code: 'PT', country: 'Portugal ' },
  { prefix: '+1-787', code: 'PR', country: 'Puerto Rico ' },
  { prefix: '+974 ', code: 'QA', country: 'Qatar, State of ' },
  {
    prefix: '+262',
    code: 'RE',
    country: 'Reunion (French) (Former Bourbon Island)',
  },
  { prefix: '+40', code: 'RO', country: 'Romania ' },
  { prefix: '+7', code: 'RU', country: 'Russian Federation ' },
  {
    prefix: '+250',
    code: 'RW',
    country: 'Rwanda (Rwandese Republic) (Former Ruanda)',
  },
  { prefix: '+290', code: 'SH', country: 'Saint Helena ' },
  {
    prefix: '+1-869',
    code: 'KN',
    country:
      'Saint Kitts and Nevis (Former Federation of Saint Christopher and Nevis)',
  },
  { prefix: '+1-758', code: 'LC', country: 'Saint Lucia ' },
  { prefix: '+508', code: 'PM', country: 'Saint Pierre and Miquelon ' },
  {
    prefix: '+1-784',
    code: 'VC',
    country: 'Saint Vincent and the Grenadines ',
  },
  { prefix: '+685', code: 'WS', country: 'Samoa (Former Western Samoa)' },
  { prefix: '+378', code: 'SM', country: 'San Marino ' },
  { prefix: '+239', code: 'ST', country: 'Sao Tome and Principe ' },
  { prefix: '+966', code: 'SA', country: 'Saudi Arabia ' },
  { prefix: '+221', code: 'SN', country: 'Senegal ' },
  { prefix: '+248', code: 'SC', country: 'Seychelles ' },
  { prefix: '+232', code: 'SL', country: 'Sierra Leone ' },
  { prefix: '+65', code: 'SG', country: 'Singapore ' },
  { prefix: '+421', code: 'SK', country: 'Slovakia' },
  { prefix: '+386', code: 'SI', country: 'Slovenia ' },
  {
    prefix: '+677',
    code: 'SB',
    country: 'Solomon Islands (Former British Solomon Islands)',
  },
  {
    prefix: '+252',
    code: 'SO',
    country: 'Somalia (Former Somali Republic, Somali Democratic Republic) ',
  },
  {
    prefix: '+27',
    code: 'ZA',
    country: 'South Africa (Former Union of South Africa)',
  },
  { prefix: '+34', code: 'ES', country: 'Spain ' },
  {
    prefix: '+94',
    code: 'LK',
    country: 'Sri Lanka (Former Serendib, Ceylon) ',
  },
  {
    prefix: '+249',
    code: 'SD',
    country: 'Sudan (Former Anglo-Egyptian Sudan) ',
  },
  {
    prefix: '+597',
    code: 'SR',
    country: 'Suriname (Former Netherlands Guiana, Dutch Guiana)',
  },
  { prefix: '+268', code: 'SZ', country: 'Swaziland, Kingdom of ' },
  { prefix: '+46', code: 'SE', country: 'Sweden ' },
  { prefix: '+41', code: 'CH', country: 'Switzerland ' },
  {
    prefix: '+963',
    code: 'SY',
    country:
      'Syria (Syrian Arab Republic) (Former United Arab Republic - with Egypt)',
  },
  { prefix: '+886', code: 'TW', country: 'Taiwan (Former Formosa)' },
  {
    prefix: '+992',
    code: 'TJ',
    country: 'Tajikistan (Former Tajik Soviet Socialist Republic)',
  },
  {
    prefix: '+255',
    code: 'TZ',
    country:
      'Tanzania, United Republic of (Former United Republic of Tanganyika and Zanzibar)',
  },
  { prefix: '+66', code: 'TH', country: 'Thailand (Former Siam)' },
  { prefix: '+690', code: 'TK', country: 'Tokelau ' },
  {
    prefix: '+676',
    code: 'TO',
    country: 'Tonga, Kingdom of (Former Friendly Islands)',
  },
  { prefix: '+1-868', code: 'TT', country: 'Trinidad and Tobago ' },
  { prefix: '+216', code: 'TN', country: 'Tunisia ' },
  { prefix: '+90', code: 'TR', country: 'Turkey ' },
  {
    prefix: '+993',
    code: 'TM',
    country: 'Turkmenistan (Former Turkmen Soviet Socialist Republic)',
  },
  { prefix: '+1-649', code: 'TC', country: 'Turks and Caicos Islands ' },
  { prefix: '+688', code: 'TV', country: 'Tuvalu (Former Ellice Islands)' },
  { prefix: '+256', code: 'UG', country: 'Uganda, Republic of' },
  {
    prefix: '+380',
    code: 'UA',
    country:
      'Ukraine (Former Ukrainian National Republic, Ukrainian State, Ukrainian Soviet Socialist Republic)',
  },
  {
    prefix: '+971',
    code: 'AE',
    country: 'United Arab Emirates (UAE) (Former Trucial Oman, Trucial States)',
  },
  { prefix: '+44', code: 'GB', country: 'United Kingdom (Great Britain / UK)' },
  { prefix: '+1', code: 'US', country: 'United States ' },
  {
    prefix: '+598',
    code: 'UY',
    country:
      'Uruguay, Oriental Republic of (Former Banda Oriental, Cisplatine Province)',
  },
  {
    prefix: '+998',
    code: 'UZ',
    country: 'Uzbekistan (Former UZbek Soviet Socialist Republic)',
  },
  { prefix: '+678', code: 'VU', country: 'Vanuatu (Former New Hebrides)' },
  { prefix: '+418', code: 'VA', country: 'Vatican City State (Holy See)' },
  { prefix: '+58', code: 'VE', country: 'Venezuela ' },
  { prefix: '+84', code: 'VN', country: 'Vietnam ' },
  { prefix: '+1-284', code: 'VI', country: 'Virgin Islands, British ' },
  {
    prefix: '+1-340',
    code: 'VQ',
    country: 'Virgin Islands, United States (Former Danish West Indies) ',
  },
  { prefix: '+681', code: 'WF', country: 'Wallis and Futuna Islands ' },
  { prefix: '+967', code: 'YE', country: 'Yemen ' },

  {
    prefix: '+260',
    code: 'ZM',
    country: 'Zambia, Republic of (Former Northern Rhodesia) ',
  },
  {
    prefix: '+263',
    code: 'ZW',
    country: 'Zimbabwe, Republic of (Former Southern Rhodesia, Rhodesia) ',
  },
]